### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Bluscream** [samuelWilliams99/BetterChat#10]

**Comment by samuelWilliams99** [comment]
Sorry, completely missed this! There's a "Clone or download" button on the top right of the main page. Hit that, download as zip, and extract it into your servers addon directory. I'd recommend getting the workshop version over that though:  
https://steamcommunity.com/sharedfiles/filedetails/?id=1841694244
As then you'll get automatic updates via steam.

**Comment by Bluscream** [comment]
Gotcha, thanks ^^
